const APPWRITE_USER_DATABASE_ID = process.env.APPWRITE_USER_DATABASE_ID;
const APPWRITE_USER_COLLECTION_ID = process.env.APPWRITE_USER_COLLECTION_ID;
const APPWRITE_BUCKER_ID = process.env.APPWRITE_BUCKER_ID;

module.exports = {
  APPWRITE_USER_DATABASE_ID,
  APPWRITE_USER_COLLECTION_ID,
  APPWRITE_BUCKER_ID,
};
